FROM --platform=linux/arm64 golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o /app/main .

FROM --platform=linux/arm64 golang:1.24

ENV TZ=Asia/Tokyo

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]
