AWSTemplateFormatVersion: '2010-09-09'
Description: Define a Role for AppLiftMessageAPI.

Resources:
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ECSTaskRoleMessageAPI
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSExecSSMMessages
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: "*"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Defined role name required for operational clarity and simplified referencing. Potential replacement risks are understood."

Outputs:
  ECSTaskRoleArn:
    Description: ARN of the ECS Task Role for AppLiftMessageAPI
    Value: !GetAtt ECSTaskRole.Arn
