AWSTemplateFormatVersion: '2010-09-09'
Description: Defines the Secrets Manager Secret for the AppLiftMessageAPI.

Resources:
  AccessTokenSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AppLiftMessageAPI/access-token-secret-key
      Description: ACCESS_TOKEN_SECRET_KEY for the AppLiftMessageAPI.
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W77
            reason: "This secret does not require cross-account sharing and using the default AWS-managed key is acceptable."
  RefreshTokenSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AppLiftMessageAPI/refresh-token-secret-key
      Description: REFRESH_TOKEN_SECRET_KEY for the AppLiftMessageAPI.
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W77
            reason: "This secret does not require cross-account sharing and using the default AWS-managed key is acceptable."

Outputs:
  AccessTokenSecretKeyArn:
    Description: The ARN of the Secrets Manager secret for AppLiftMessageAPI ACCESS_TOKEN_SECRET_KEY.
    Value: !Ref AccessTokenSecretKey
    Export:
      Name: !Sub "${AWS::StackName}-AccessTokenSecretKeyArn"
  RefreshTokenSecretKeyArn:
    Description: The ARN of the Secrets Manager secret for AppLiftMessageAPI REFRESH_TOKEN_SECRET_KEY.
    Value: !Ref RefreshTokenSecretKey
    Export:
      Name: !Sub "${AWS::StackName}-RefreshTokenSecretKeyArn"
